### ISSUE TITLE
GLib Value with string[] not working

### ISSUE THREAD

**Issue by uler3161** [GLibSharp/GtkSharp#83]
I've asked GStreamer devs about this, but no response. See https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3558 and https://discourse.gstreamer.org/t/gstreamer-sharp-signal-with-string-array-return-value/1614

Simply put, all I'm trying to do is provide a string[] to GStreamer using GStreamer-Sharp. I don't really know where the issue is, but it's getting corrupted at some point. GStreamer prints a smiley face to the console and an SOH character to the log. 

Here is some testing code:

```
var val = new[] { "D:/VideoRecording/Ubiquiti 1/video0000000.mp4" };
var glibValue = new GLib.Value(val);
foreach (var item in (string[])glibValue.Val)
{
    Logger.LogWarning(item);
}
```

This portion takes GStreamer out of the equation. All I'm trying to do here is to create a GLib.Value for my string array, then get it back and print it out. But I get this:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Unknown type GStrv
   at GLib.Value.ToBoxed()
   at GLib.Value.get_Val()
```

That might be a separate problem, but I just don't know. It does make me wonder if this library handles GStrv correctly. And since the GStreamer api I'm using requires a GStrv*, I'm thinking the problem is with this library and not GStreamer. Any suggestions?

**Comment by uler3161** [comment]
Apparently if I use `(string[])glibValue` instead of `(string[])glibValue.Val`, it works. Still doesn't help the main problem with GStreamer ending up with a corrupted value.

**Comment by uler3161** [comment]
Also, scratch that on the GStreamer api using GStrv*. Their online docs were wrong. It says gchar** now.
